### ISSUE TITLE
CSS Not Reading d : path("");

### ISSUE THREAD

**Issue by N-Efron** [cdaein/mica-gd431#3]
In my project I want to my SVGs to change path when one hovers above them, but I realized that my css was not recognizing the d tag? 
<img width="1087" alt="Screen Shot 2019-10-21 at 5 31 20 PM" src="https://user-images.githubusercontent.com/54686719/67244846-a411a600-f428-11e9-95fb-8bef16b74195.png">

Once I commented out the .waveOne:hover{d : path("");} my media query, which was originally not working was now able to work. 

I would design around that, except that my text has an irregular shape to it, and it is an SVG, and the way I am planning on stacking it in different viewport sizes is by changing the path in the CSS, so I would love to be able to use the d tag. 

Is there some syntax I am missing? How can I get the d tag to work

**Comment by cdaein** [comment]
hard to tell without looking at your HTML code, but will you check where you applied the hover? Was it on `<svg>` or `<path>`? Because I think `:hover` selector only works on the svg.

So, if you need your SVG path to animate, then the selector will look something like this:

```css
svg:hover .waveOned {
  d: path();
}
```
